# Generated by Django 3.0.2 on 2020-01-31 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='user_profiles',
            field=models.ManyToManyField(null=True, related_name='favorite_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
