# Generated by Django 3.0.2 on 2020-01-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthdy',
            field=models.DateField(null=True),
        ),
    ]
