# Generated by Django 3.0.2 on 2020-01-29 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0002_auto_20200128_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birthdy',
            new_name='birthday',
        ),
    ]
