# Generated by Django 3.0.2 on 2020-01-29 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0003_auto_20200129_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField()),
                ('user_profiles', models.ManyToManyField(null=True, related_name='favorite_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
