# Generated by Django 3.0.2 on 2020-01-31 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0004_auto_20200131_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platform',
            old_name='platfrom_abbreviation',
            new_name='platform_abbreviation',
        ),
        migrations.RenameField(
            model_name='platform',
            old_name='platfrom_name',
            new_name='platform_name',
        ),
    ]
