# Generated by Django 3.0.2 on 2020-01-31 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField()),
<<<<<<< .merge_file_gfY98t
                ('game_name', models.CharField(max_length=200)),
                ('cover_url', models.URLField(null=True)),
                ('user_rating', models.IntegerField(null=True)),
                ('user_rating_count', models.IntegerField(null=True)),
                ('critic_rating', models.IntegerField(null=True)),
                ('critic_rating_count', models.IntegerField(null=True)),
                ('game_description', models.TextField(null=True)),
                ('game_release_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_thumb_url', models.URLField()),
                ('screen_big_url', models.URLField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='games.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_id', models.IntegerField()),
                ('platfrom_name', models.CharField(max_length=100)),
                ('platfrom_abbreviation', models.CharField(max_length=20, null=True)),
                ('game', models.ManyToManyField(related_name='platforms', to='games.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_id', models.IntegerField()),
                ('Keyword_name', models.CharField(max_length=100)),
                ('game', models.ManyToManyField(related_name='keywords', to='games.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.IntegerField()),
                ('genre_name', models.CharField(max_length=100)),
                ('game', models.ManyToManyField(related_name='genres', to='games.Game')),
=======
>>>>>>> .merge_file_88Op1t
            ],
        ),
    ]
