# Generated by Django 3.0.2 on 2020-02-05 10:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='user_profiles',
            field=models.ManyToManyField(null=True, related_name='favorite_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
