# Generated by Django 3.0.2 on 2020-02-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_user_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='keyword_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='platform_id',
            field=models.IntegerField(unique=True),
        ),
    ]
