# Generated by Django 3.0.2 on 2020-01-31 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20200131_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='Keyword_name',
            new_name='keyword_name',
        ),
    ]
