# Generated by Django 3.0.2 on 2020-02-10 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20200205_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='game',
            new_name='games',
        ),
        migrations.RenameField(
            model_name='keyword',
            old_name='game',
            new_name='games',
        ),
        migrations.RenameField(
            model_name='platform',
            old_name='game',
            new_name='games',
        ),
    ]
