# Generated by Django 3.0.2 on 2020-02-27 15:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0004_auto_20200210_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='user_profiles',
            field=models.ManyToManyField(related_name='favorite_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
